import type { OrderDTO } from "@medusajs/framework/types";

/**
 * Mock order data for email template previews
 */
export const mockOrder = {
  id: "order_01K639QM8W1G6SR2BB876GZJ59",
  status: "pending",
  created_at: "2025-09-26T15:19:42.621Z",
  canceled_at: null,
  email: "customer@example.com",
  display_id: 885,
  custom_display_id: null,
  currency_code: "ron",
  metadata: null,
  total: 6850,
  credit_line_total: 0,
  item_subtotal: 6500,
  item_total: 6500,
  item_tax_total: 0,
  original_item_tax_total: 0,
  item_discount_total: 0,
  shipping_subtotal: 350,
  original_total: 6850,
  original_tax_total: 0,
  subtotal: 6850,
  discount_total: 0,
  discount_subtotal: 0,
  shipping_total: 350,
  shipping_tax_total: 0,
  original_shipping_tax_total: 0,
  shipping_discount_total: 0,
  tax_total: 0,
  summary: {
    paid_total: 0,
    difference_sum: 0,
    raw_paid_total: { value: "0", precision: 20 },
    refunded_total: 0,
    transaction_total: 0,
    pending_difference: 6850,
    raw_difference_sum: { value: "0", precision: 20 },
    raw_refunded_total: { value: "0", precision: 20 },
    current_order_total: 6850,
    original_order_total: 6850,
    raw_transaction_total: { value: "0", precision: 20 },
    raw_pending_difference: { value: "6850", precision: 20 },
    raw_current_order_total: { value: "6850", precision: 20 },
    raw_original_order_total: { value: "6850", precision: 20 },
  },
  version: 1,
  region_id: "reg_01J9BARYJPG4N23XB9MDFASMNT",
  customer_id: "cus_01K639NK56K7QC1YHQDRTJZMKF",
  sales_channel_id: "sc_01J99451DMEJ0BYTMQ44NEQ8N0",
  items: [
    {
      id: "ordli_01K639QM8WKDKH0NN14J8ECV8Q",
      title: "Single Panel",
      subtitle: "SunPower Mono 400W Panel",
      thumbnail:
        "https://placehold.co/800x800/FFF6E6/FF5227?text=SunPower+400W",
      variant_id: "variant_01J9RZETCBAZT6RCYD7D0EEPCC",
      product_id: "prod_01J9A51JXCGGCWQZYYACDZ2V0H",
      product_title: "SunPower Mono 400W Panel",
      product_description:
        "High-efficiency 400W monocrystalline solar panel with 21.4% cell efficiency. PERC technology for superior low-light performance.",
      product_subtitle: "High-efficiency monocrystalline panel",
      product_type: "Solar Panel",
      product_handle: "sunpower-mono-400w",
      variant_sku: "SP-MONO-400-1",
      variant_title: "Single Panel",
      requires_shipping: true,
      is_giftcard: false,
      is_discountable: true,
      is_tax_inclusive: false,
      unit_price: 1450,
      quantity: 4,
      subtotal: 5800,
      total: 5800,
      original_subtotal: 5800,
      original_total: 5800,
      discount_total: 0,
      tax_total: 0,
    },
    {
      id: "ordli_01K639QM8W34XC7T4KPJ6Y19TB",
      title: "10m Kit",
      subtitle: "SolarLink MC4 Cable Kit",
      thumbnail:
        "https://placehold.co/800x800/FFF6E6/FF5227?text=MC4+Cable+Kit",
      variant_id: "variant_01J9RY4RD0SCXHKMF0HE85WREF",
      product_id: "prod_01J9A2QYCBTAQT3XN27XDTH8EX",
      product_title: "SolarLink MC4 Cable Kit",
      product_description:
        "Complete MC4 solar cable connection kit with UV-resistant solar cable, MC4 connectors, and crimping tool.",
      product_subtitle: "Complete solar cable connection kit",
      product_type: "Cable Kit",
      product_collection: "Cables & Connectors",
      product_handle: "solarlink-mc4-cable-kit",
      variant_sku: "SL-MC4-10",
      variant_title: "10m Kit",
      requires_shipping: true,
      is_giftcard: false,
      is_discountable: true,
      is_tax_inclusive: false,
      unit_price: 280,
      quantity: 1,
      subtotal: 280,
      total: 280,
      original_subtotal: 280,
      original_total: 280,
      discount_total: 0,
      tax_total: 0,
    },
  ],
  shipping_address: {
    id: "caaddr_01K639NK63P8JCBM86APZZ823V",
    customer_id: null,
    company: "SolarEdge Supply SRL",
    first_name: "John",
    last_name: "Doe",
    address_1: "Str. Energiei Nr. 42",
    address_2: "",
    city: "Bucharest",
    country_code: "ro",
    province: "B",
    postal_code: "010101",
    phone: null,
    metadata: null,
    created_at: "2025-09-26T15:18:35.971Z",
    updated_at: "2025-09-26T15:18:35.971Z",
    deleted_at: null,
  },
  billing_address: {
    id: "caaddr_01K639NK63P8JCBM86APZZ824V",
    customer_id: null,
    company: "SolarEdge Supply SRL",
    first_name: "John",
    last_name: "Doe",
    address_1: "Str. Energiei Nr. 42",
    address_2: "",
    city: "Bucharest",
    country_code: "ro",
    province: "B",
    postal_code: "010101",
    phone: null,
    metadata: null,
    created_at: "2025-09-26T15:18:35.971Z",
    updated_at: "2025-09-26T15:18:35.971Z",
    deleted_at: null,
  },
  shipping_methods: [
    {
      id: "ordsm_01K639QM8W3J96SMBN3EGMWE7H",
      name: "Express Shipping",
      description: null,
      is_tax_inclusive: false,
      shipping_option_id: "so_01JABKG19CB81NN1EZYVJ8N5FC",
      amount: 350,
      subtotal: 350,
      total: 350,
      original_subtotal: 350,
      original_total: 350,
      discount_total: 0,
      tax_total: 0,
    },
  ],
  fulfillments: [],
  payment_status: "authorized",
  fulfillment_status: "not_fulfilled",
} as unknown as OrderDTO;
